/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * myTextOutputJFrame.java
 *
 * Created on Mar 4, 2010, 2:28:40 PM
 */

package gridGenerator;
import java.io.PrintWriter;

/**
 *
 * @author roudnev
 */
public class MyTextOutputJFrame extends javax.swing.JFrame {
    PrintWriter out;

    /** Creates new form myTextOutputJFrame */
    public MyTextOutputJFrame() {
        initComponents();
        this.out=new PrintWriter( new TextAreaWriter(this.getJTextArea1()));
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(main.ThreeBodySolverConfiguratorApp.class).getContext().getResourceMap(MyTextOutputJFrame.class);
    setTitle(resourceMap.getString("Form.title")); // NOI18N
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setMinimumSize(new java.awt.Dimension(400, 298));
    setName("Form"); // NOI18N

    jScrollPane1.setAutoscrolls(true);
    jScrollPane1.setDoubleBuffered(true);
    jScrollPane1.setName("jScrollPane1"); // NOI18N

    jTextArea1.setColumns(80);
    jTextArea1.setEditable(false);
    jTextArea1.setFont(resourceMap.getFont("jTextArea1.font")); // NOI18N
    jTextArea1.setRows(5);
    jTextArea1.setDoubleBuffered(true);
    jTextArea1.setMinimumSize(new java.awt.Dimension(880, 27));
    jTextArea1.setName("jTextArea1"); // NOI18N
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyTextOutputJFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables

  /**
   * @return the jTextArea1
   */
  public javax.swing.JTextArea getJTextArea1()
  {
    return jTextArea1;
  }

  /**
   * @param jTextArea1 the jTextArea1 to set
   */
  public void setJTextArea1(javax.swing.JTextArea jTextArea1)
  {
    this.jTextArea1 = jTextArea1;
  }

}
